import clsx from 'clsx';
import { Geist, Geist_Mono } from 'next/font/google';
import { Navbar } from '../components/Navbar';
import '../styles/globals.css';
import { Providers } from './providers';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={clsx(
          `min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`,
        )}>
        <Providers themeProps={{ attribute: 'class' }}>
          <div className='relative flex flex-col h-screen '>
            <Navbar />
            {/* <nav className=''>
              <Link href={'/'}>Home</Link>
              <Link href={'/about'}>About</Link>
              <Link href={'/categories'}>categories</Link>
              <Link href={'/projects'}>Projects</Link>
              {/* <ThemeSwitch /> 
            </nav> */}
            <main className='container max-w-7xl px-6 flex-grow'>
              {children}
            </main>
            {/* <ThemeSwitcher /> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
