import clsx from 'clsx';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { Navbar } from '../components/Navbar';
import '../styles/globals.css';
import { Providers } from './providers';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const inter = Inter({
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning className=''>
      <body
        className={clsx(
          `min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`,
        )}>
        <Providers themeProps={{ attribute: 'class' }}>
          <div className='relative flex flex-col h-screen w-screen'>
            <Navbar />
            <main className='w-full max-w-9xl px-l py-l flex-grow'>
              {children}
            </main>
            <footer className='row-start-3 flex gap-6 flex-wrap items-center justify-center'>
              <small>&copy; 2025 My Portfolio. All rights reserved.</small>
            </footer>
            {/* <ThemeSwitcher /> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
